config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'
  devise_for :users

  resources :articles do
    resources :comments
  end

  get 'about' => 'about#show'
  get 'service' => 'services#index'
  get 'service/use_script' => 'services#use_script'
  get 'service/use_react' => 'services#use_react'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}

  # Elasticsearchのマッピングを設定
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :content, analyzer: 'english'
    end
  end

  def as_indexed_json(options={})
    self.as_json(
      only: [:title, :content]
    )
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def show; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(title: "...", body: "...")
    
    if @article.save
      redirect_to @article
    else
      render :new, status: unprocessable_entity
    end
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy

    redirect_to articles_index_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find_by(id: params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find_by(id: params[:article_id])
    @comment = @article.comments.find_by(id: params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  def index; end

  def use_script; end

  def use_importmap; end

  def use_react; end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index; end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/views/about/show.html.erb
<% content_for :body do %>
  <form name="login_form">
    <div class="login_form_top">
      <h1>ABOUT</h1>
      <p>Ruby on Rails を用いたサンプルWebアプリです</p>
    </div>
  </form>
  <%= stylesheet_link_tag "about" %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status%><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Articles</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<% content_for :body do %>
<div>
  <h1>Articles</h1>

  <p>Our blog has <%= Article.public_count %> articles and counting!</p>

  <br>
  <ul>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <li>
         <%= link_to article.title, article %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <br>
  <%= link_to "New Article", new_article_path %>

</div>
<%= stylesheet_link_tag "article" %>
<% end %>

app/views/articles/new.html.erb
<h1>New Articles</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Show Articles</h1>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <h1>
        <a href="/">Chokk App</a>
    </h1>
    <nav class="pc-nav">
        <ul>
            <li><a href="/about">ABOUT</a></li>
            <li><a href="/service">SERVICE</a></li>
        </ul>
    </nav>
</header>

<%= stylesheet_link_tag "header_styles" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Ruby App</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>        
        
        <%= yield :head %>
        <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    </head>

    <body>
        <%= render 'layouts/header' %>
        <% if flash[:notice] %>
            <div class="notification is-info">
                <p class="notice"><%= notice %></p>
            </div>
        <% end %>
        <% if flash[:alert] %>
            <div class="notification is-danger">
            <p class="alert"><%= alert %></p>
            </div>
        <% end %>
        <main>
        <%= yield :body %>
        </main>
     </body>
</html>

app/views/services/index.html.erb
<% content_for :body do %>
  <form name="login_form">
    <div class="login_form_top">
      <h1>SERVICE</h1>
        <ul>
          <li><a href="service/use_script">Counter</a></li>
          <li><a href="articles">Articles</a></li>
        </ul>
    </div>
  </form>
  
  <%= stylesheet_link_tag "about" %>
<% end %>

app/views/services/use_react.html.erb
<% content_for :body do %>
  <form name="service_form">
    <p>reactを用いたページです</p>
    <%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>
  </form>
<% end %>

app/views/services/use_script.html.erb
<% content_for :head do %>
  <script src="https://unpkg.com/react@16/umd/react.development.js">
  </script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js">
  </script>
<% end %>

<% content_for :body do %>
  <div>
    <script>
      window.onload = function () {
      alert("<script>を使ったページです");
      };
    </script>
  
    <h1>Counter</h1>
    <div id="root" onclick="doCount();">wait...</div>
    <script>
    let counter = 0
    let dom = document.querySelector('#root')
    doCount()

    function doCount() {
      counter++
      let element = React.createElement(
        'p', {}, "count: " + counter
      )
      ReactDOM.render(element, dom)
    }
    </script>
  </div>

  <%= stylesheet_link_tag "service" %>
<% end %>

app/views/top/index.html.erb
<% content_for :head do %>
  <title>Login</title>
<% end %>

<% content_for :body do %>
  <form name="login_form">
    <div class="login_form_top">
      <h1>LOGIN</h1>
    </div>
    <div class="login_form_btm">
      <input type="id" name="user_id" placeholder="ID">
      <input type="password" name="password" placeholder="Password">
      <input type="submit" name="botton" value="LOGIN">
    </div>
  </form>

  <%= stylesheet_link_tag "top" %>
<% end %>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピグラマー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.recipes.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このレシピを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>